image: python:3.9

stages:
  - test
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/
    - venv/

before_script:
  - python -V
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - pip install pytest pytest-cov
    - pytest tests/ --cov=app/
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

build:
  stage: build
  script:
    - pip install build
    - python -m build
  artifacts:
    paths:
      - dist/
  only:
    - main

deploy_streamlit:
  stage: deploy
  script:
    - pip install streamlit-cloud-client
    - |
      if [ ! -z "$STREAMLIT_API_KEY" ]; then
        echo "Deploying to Streamlit Cloud..."
        streamlit deploy app/resume_agent.py \
          --api-key $STREAMLIT_API_KEY \
          --project-name resume-agent
      else
        echo "STREAMLIT_API_KEY not set. Skipping deployment."
        exit 1
      fi
  environment:
    name: production
    url: https://resume-agent.streamlit.app
  only:
    - main
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure 